# Generated by Django 4.1 on 2022-08-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuteachapp', '0002_student_user_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dateofbirth',
        ),
    ]
